from commands import *
import acorn


load(0x0400, "../../4-reference-binaries/pias/TheSentinel.bin")
set_output_filename("TheSentinel.bin")
acorn.bbc()
config.set_lower_case(False)
config.set_label_references(False)
#config.set_hex_dump(False)
config.set_show_autogenerated_labels(False)
config.set_show_all_labels(False)
config.set_indent_string(" ")
config.set_show_stats(False)

################################################################################
# ZERO PAGE
################################################################################

label(0x0070, "P")
label(0x0071, "Q")
label(0x0072, "R")
label(0x0073, "S")

################################################################################
# ENTRY CODE
################################################################################

entry(0x3F04, "Begin")

entry(0x6D00 - 0x1900 + 0x0400, "Entry")

go()
